version: '3.0'

services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    command: rackup -p 3000 --host 0.0.0.0
    stdin_open: true
    tty: true

  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - './db/data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=bank
      - MYSQL_USER=bank_api
      - MYSQL_PASSWORD=capalbo
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
